### PR TITLE
Feature: add use memory store

### PR DESCRIPTION
**Pull request by aferditamuriqi**

### CODE REVIEW

**Comment by gotson** [comment]
@aferditamuriqi  i feel like this is only changing the fallback store, but not the default store. I haven't tested, but looking at the code it seems it would still store settings in the local storage.

**Comment by aferditamuriqi** [comment]
@gotson it doesn't I've tested it, just see my comment in the index file

**Comment by gotson** [comment]
> @gotson it doesn't I've tested it, just see my comment in the index file

LGTM, tested and it works. Thanks.

**Comment by aferditamuriqi** [comment]
> > @gotson it doesn't I've tested it, just see my comment in the index file
> 
> LGTM, tested and it works. Thanks.

you ok, with me using this PR instead of yours?

**Comment by gotson** [comment]
> > > @gotson it doesn't I've tested it, just see my comment in the index file
> > 
> > 
> > LGTM, tested and it works. Thanks.
> 
> you ok, with me using this PR instead of yours?

sure

**Pull request merged**
